feat(update): update pipeline

diff --git a/.github/workflows/pipeline-husky.yml b/.github/workflows/pipeline-husky.yml
--- a/.github/workflows/pipeline-husky.yml
+++ b/.github/workflows/pipeline-husky.yml
@@ -7,7 +7,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: git clone https://github.com/khadija-AC/husky-project.git
+        uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: npm install node
@@ -16,5 +16,34 @@ jobs:
 
       - name: Install dependencies
         run: npm install
+
+      - name: ls
+        run: ls -a
+
+      - name: identification
+        run: |
+          git config --global user.email "khadijaaws21@gmail.com"
+          git config --global user.name "khadija-AC"
+
+      - name: Permission
+        run: |
+         chmod +x .husky/pre-commit
+         chmod +x .husky/commit-msg
+         chmod +x .husky/prepare-commit-msg
+      
+     
+      - name: Add Changes
+        run: |
+          git add .
+          git commit -m "feat: add test for husky integration"
+      
+      - name: Verification(cat index.js)
+        run: cat index.js
+
+      - name: Comment on PR if lint fails
+        if: ${{ failure() }}
+        run: |
+          echo "Lint checks failed. Please review and fix the issues."
+          exit 1
 
       
